### ISSUE TITLE
Math mode font issue

### ISSUE THREAD

**Issue by chang48** [martenlienen/pelican-katex#12]
Firstly, thanks for creating this wonderful plugin! Let me describe the problem in the following.

- pelican: 4.8.0
- pelican-katex: 1.6.1

Math model font issue, example:
<img width="567" alt="Screenshot 2023-05-10 at 6 33 43 PM" src="https://github.com/martenlienen/pelican-katex/assets/2575869/2f04bf73-cec6-4159-aec1-749ebd321e74">

In math mode (in-line or block), I was expecting the notations to be italic, instead all of them were upright. The font didn't look like **Computer Modern** either. In addition, the command `\cal` didn't seem to be working. In the example, `{\cal D}` was supposed to be a cursive `D`. I was expecting something like:
<img width="388" alt="_f(z_0)_=_frac_" src="https://github.com/martenlienen/pelican-katex/assets/2575869/2678ae48-f9fe-4eb9-a2fc-e6072529985a">

I think this is a simple font setting issue. Somehow the out-of-the-box setting didn't work. Is there a way to fix this? Thanks!

**Comment by chang48** [comment]
I put the stylesheet 
`<link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/katex/dist/katex.min.css"
      crossorigin="anonymous">`
in `base.html` of my theme. 

Did that mess up the font style?

**Comment by martenlienen** [comment]
`\cal` has only been supported [since KaTeX 0.12](https://github.com/KaTeX/KaTeX/blob/main/CHANGELOG.md), but I have not updated the version that comes with pelican-katex in a while. I should be able to update it by the end of the month, though you can do it yourself as described in [the readme](https://github.com/martenlienen/pelican-katex#configuration) by setting a `KATEX_PATH` to a local copy of a more recent `katex.js`. That might also be the reason why the styling is not working correctly. Maybe the stylesheets changed between versions 0.11 and 0.16.

**Comment by martenlienen** [comment]
I have just pushed a new version 1.7.0 to PyPI that bundles the latest katex 0.16.7, so your LaTeX should work now out of the box.

**Comment by chang48** [comment]
> I have just pushed a new version 1.7.0 to PyPI that bundles the latest katex 0.16.7, so your LaTeX should work now out of the box.

Thank you for the update. Unfortunately the problem still persists. My setup now looks like the following:

- pelican: 4.8.0
- pelican-katex: 1.7.0
- nodejs: 0.1.1

I have a few question about the installation procedure that I hope you could help clarify:

- When it is mentioned "remove the `katex.js` `<script>` tag from your template," what template is it referring to? Is it the template of my current theme?
- Regarding "need to include the KaTeX stylesheets with your website," I copied your example and added it to the 'base.html' of the [Flex](https://github.com/alexandrevicenzi/Flex) theme. Is this the correct place?

Thanks!

**Comment by martenlienen** [comment]
You only have to remove the tag, if you used katex before in the usual way with client-side loading. If you have never added the katex `script` tag, you also don't need to remove it. Also your nodejs version is **really** old. Where can you even install something like this anymore? The oldest version [available on their website](https://nodejs.org/en/download/releases) is 0.12.8 which is 6 years old by now and long out of maintenance.

Does the problem persists in its entirety, i.e. is the `\cal` still shown in red? If so, it is not using the new katex version that comes with pelican-katex 1.7.0. If only the font is wrong, I suspect that the stylesheet that you included is not loaded for some reason. Have you tried to delete the build folder and rebuild/recompile your website from scratch with `pelican`?

**Comment by chang48** [comment]
Thanks for the prompt reply! For the formula shown in the first inquiry, I was expecting the following output:

<img width="282" alt="Screenshot 2023-05-29 at 11 33 36 PM" src="https://github.com/martenlienen/pelican-katex/assets/2575869/56bab1f7-6ca2-4c1f-b220-a45a55a36f9e">

However, all the symbols are not italic. 

About the nodejs, you are absolute correct! I installed in through pypi on which the latest version is 0.11. I should've installed it via anaconda. I'll fix the nodejs installation.

**Comment by chang48** [comment]
The '\cal' is still shown in red. So something is wrong in my pelican-katex installation.

**Comment by martenlienen** [comment]
If the red `\cal` disappeared, the issue should be that the stylesheet cannot be loaded. You could check out some of these repositories that use pelican-katex and see, how they have included it: https://github.com/martenlienen/pelican-katex/network/dependents

And the `p` and `d` on my website are non-italic on purpose :)

**Comment by martenlienen** [comment]
Have you tried reinstalling pelican-katex?

**Comment by chang48** [comment]
Thanks for the tips. I'll go through the sample websites and look at pelican-katex implementation details.

**Comment by chang48** [comment]
Hi Marten, I'm here to report that my `pelican-katex` plugin is working now, as shown in this screenshot:

<img width="743" alt="Screenshot 2023-05-30 at 6 38 37 PM" src="https://github.com/martenlienen/pelican-katex/assets/2575869/4863dacb-f738-44fe-90a1-fa5898fed4c1">

Thanks for your help along the way! Here is a list of changes I implemented
- Installed the latest `node.js` through `homebrew`. It turned out the `node.js` I installed through `pip` is just a python binding. This is probably one of the major mistakes I made.
- Copied the latest `katex.js` bundled in `pelican-katex` to my pelican plugin folder located in my venv: `miniforge3/envs/nlp/lib/python3.9/site-packages/pelican/plugins/pelican_katex/` which I forgot to update after you pushed v1.7.0. 
- Lastly, linked the stylesheet `katex.min.css` from [this link](https://www.jsdelivr.com/package/npm/katex). 

At one point, I thought I needed to install `katex` via `npm`. As it turned out the LaTeX rendering just worked without it. So I'll leave it for the moment. The samples your provided are helpful, especially the source of [jzc.github.io](https://github.com/jzc/jzc.github.io).Some of the samples appear to me don't actually have any LaTeX math in their blog posts, just FYI.

Again, thanks for creating this plugin!
